# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Build Drivers

on:
    branches:
      - master
      - develop #prerelease nugets

defaults:
  run:
    shell: pwsh

jobs:
  build-drivers:
    name: Build MBN Click Drivers
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      solution: '**/nanoFramework.ClickDrivers.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      classLibName: 'nanoFramework.MikroClick.Drivers'
      nugetPackageName: 'nanoFramework.MikroClick.Drivers'
      repoName: 'MBN-TinyCLR' #repoName: 'lib-nanoFramework-MikroClick-Drivers'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          path: main
      - name: Checkout tools repo
        uses: actions/checkout@v2.3.1
        with:
          repository: nanoframework/nf-tools
          path: tools
